NAME		= Sed

			= c++
FLAGS	= -Wall -Wextra -Werror -std=c++98

SRC			= main.cpp Sed.cpp
OBJ			= $(SRC:.cpp=.o)

all:$(NAME)
$(NAME):$(OBJ)
	$() $(FLAGS) $(OBJ) -o $(NAME)

clean:
	rm -rf $(OBJ)

fclean:clean
	rm -rf $(NAME)
re:fclean all
.PHONY: re all fclean clean